(defun get-track-points (file)
  (with-open-file (s file :direction :input)
    (let* ((gpx (xmls:parse s))
           (trk (xmls:xmlrep-find-child-tag "trk" gpx))
           (trkseg (xmls:xmlrep-find-child-tag "trkseg" trk)))
      (mapcar #'(lambda (node)
                  (list (read-from-string (xmls:xmlrep-attrib-value "lat" node))
                        (read-from-string (xmls:xmlrep-attrib-value "lon" node))))
              (xmls:xmlrep-find-child-tags "trkpt" trkseg)))))
